apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopping-copilot-sa
  namespace: techx-tf3
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::197826770971:role/shopping-copilot-eks-role
