apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopping-copilot-sa
  namespace: techx-tf3
  labels:
    app: shopping-copilot
    team: aie2
  annotations:
    # CDO điền ARN của IAM Role đã tạo cho IRSA
    eks.amazonaws.com/role-arn: "arn:aws:iam::197826770971:role/shopping-copilot-eks-role"
