# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import accounting_pb2 as accounting__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in accounting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountingStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/accounting.Accounting/CreateOrder',
                request_serializer=accounting__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=accounting__pb2.Order.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/accounting.Accounting/GetOrder',
                request_serializer=accounting__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=accounting__pb2.Order.FromString,
                _registered_method=True)
        self.AddOrderItem = channel.unary_unary(
                '/accounting.Accounting/AddOrderItem',
                request_serializer=accounting__pb2.AddOrderItemRequest.SerializeToString,
                response_deserializer=accounting__pb2.OrderItem.FromString,
                _registered_method=True)
        self.SetShipping = channel.unary_unary(
                '/accounting.Accounting/SetShipping',
                request_serializer=accounting__pb2.SetShippingRequest.SerializeToString,
                response_deserializer=accounting__pb2.Shipping.FromString,
                _registered_method=True)
        self.GetShipping = channel.unary_unary(
                '/accounting.Accounting/GetShipping',
                request_serializer=accounting__pb2.GetShippingRequest.SerializeToString,
                response_deserializer=accounting__pb2.Shipping.FromString,
                _registered_method=True)
        self.DeleteOrder = channel.unary_unary(
                '/accounting.Accounting/DeleteOrder',
                request_serializer=accounting__pb2.DeleteOrderRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AccountingServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddOrderItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetShipping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShipping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=accounting__pb2.CreateOrderRequest.FromString,
                    response_serializer=accounting__pb2.Order.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=accounting__pb2.GetOrderRequest.FromString,
                    response_serializer=accounting__pb2.Order.SerializeToString,
            ),
            'AddOrderItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOrderItem,
                    request_deserializer=accounting__pb2.AddOrderItemRequest.FromString,
                    response_serializer=accounting__pb2.OrderItem.SerializeToString,
            ),
            'SetShipping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetShipping,
                    request_deserializer=accounting__pb2.SetShippingRequest.FromString,
                    response_serializer=accounting__pb2.Shipping.SerializeToString,
            ),
            'GetShipping': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShipping,
                    request_deserializer=accounting__pb2.GetShippingRequest.FromString,
                    response_serializer=accounting__pb2.Shipping.SerializeToString,
            ),
            'DeleteOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOrder,
                    request_deserializer=accounting__pb2.DeleteOrderRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accounting.Accounting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accounting.Accounting', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Accounting:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting.Accounting/CreateOrder',
            accounting__pb2.CreateOrderRequest.SerializeToString,
            accounting__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting.Accounting/GetOrder',
            accounting__pb2.GetOrderRequest.SerializeToString,
            accounting__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddOrderItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting.Accounting/AddOrderItem',
            accounting__pb2.AddOrderItemRequest.SerializeToString,
            accounting__pb2.OrderItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetShipping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting.Accounting/SetShipping',
            accounting__pb2.SetShippingRequest.SerializeToString,
            accounting__pb2.Shipping.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShipping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting.Accounting/GetShipping',
            accounting__pb2.GetShippingRequest.SerializeToString,
            accounting__pb2.Shipping.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting.Accounting/DeleteOrder',
            accounting__pb2.DeleteOrderRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
