# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x15SearchProductsRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\xa4\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07picture\x18\x04 \x01(\t\x12\x1b\n\x13price_currency_code\x18\x05 \x01(\t\x12\x13\n\x0bprice_units\x18\x06 \x01(\x03\x12\x13\n\x0bprice_nanos\x18\x07 \x01(\x05\x12\x12\n\ncategories\x18\x08 \x01(\t\";\n\x14ListProductsResponse\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.products.Product2\xe3\x01\n\x08Products\x12<\n\nGetProduct\x12\x1b.products.GetProductRequest\x1a\x11.products.Product\x12\x46\n\x0cListProducts\x12\x16.google.protobuf.Empty\x1a\x1e.products.ListProductsResponse\x12Q\n\x0eSearchProducts\x12\x1f.products.SearchProductsRequest\x1a\x1e.products.ListProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=57
  _globals['_GETPRODUCTREQUEST']._serialized_end=88
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_start=90
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_end=128
  _globals['_PRODUCT']._serialized_start=131
  _globals['_PRODUCT']._serialized_end=295
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=297
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=356
  _globals['_PRODUCTS']._serialized_start=359
  _globals['_PRODUCTS']._serialized_end=586
# @@protoc_insertion_point(module_scope)
