# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product_reviews.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'product_reviews.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15product_reviews.proto\x12\x0fproduct_reviews\x1a\x1bgoogle/protobuf/empty.proto\"_\n\x13\x43reateReviewRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x01\"\x1e\n\x10GetReviewRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"(\n\x12ListReviewsRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"i\n\x13UpdateReviewRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x18\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05score\x18\x03 \x01(\x01H\x01\x88\x01\x01\x42\x0e\n\x0c_descriptionB\x08\n\x06_score\"!\n\x13\x44\x65leteReviewRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"^\n\x06Review\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\x01\"?\n\x13ListReviewsResponse\x12(\n\x07reviews\x18\x01 \x03(\x0b\x32\x17.product_reviews.Review2\xa8\x03\n\x0eProductReviews\x12M\n\x0c\x43reateReview\x12$.product_reviews.CreateReviewRequest\x1a\x17.product_reviews.Review\x12G\n\tGetReview\x12!.product_reviews.GetReviewRequest\x1a\x17.product_reviews.Review\x12\x61\n\x14ListReviewsByProduct\x12#.product_reviews.ListReviewsRequest\x1a$.product_reviews.ListReviewsResponse\x12M\n\x0cUpdateReview\x12$.product_reviews.UpdateReviewRequest\x1a\x17.product_reviews.Review\x12L\n\x0c\x44\x65leteReview\x12$.product_reviews.DeleteReviewRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_reviews_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREVIEWREQUEST']._serialized_start=71
  _globals['_CREATEREVIEWREQUEST']._serialized_end=166
  _globals['_GETREVIEWREQUEST']._serialized_start=168
  _globals['_GETREVIEWREQUEST']._serialized_end=198
  _globals['_LISTREVIEWSREQUEST']._serialized_start=200
  _globals['_LISTREVIEWSREQUEST']._serialized_end=240
  _globals['_UPDATEREVIEWREQUEST']._serialized_start=242
  _globals['_UPDATEREVIEWREQUEST']._serialized_end=347
  _globals['_DELETEREVIEWREQUEST']._serialized_start=349
  _globals['_DELETEREVIEWREQUEST']._serialized_end=382
  _globals['_REVIEW']._serialized_start=384
  _globals['_REVIEW']._serialized_end=478
  _globals['_LISTREVIEWSRESPONSE']._serialized_start=480
  _globals['_LISTREVIEWSRESPONSE']._serialized_end=543
  _globals['_PRODUCTREVIEWS']._serialized_start=546
  _globals['_PRODUCTREVIEWS']._serialized_end=970
# @@protoc_insertion_point(module_scope)
